# Generated by Django 4.0.6 on 2022-07-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
