# Generated by Django 4.0.6 on 2022-07-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_category_women_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='slug',
        ),
    ]
